{{ template "elk.settings.all.prepare" . -}}
{{- if .Values.general.pkiInitEnabled }}
#
# Copyright 2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "elasticsearch.fullname" . }}-pki-init"
  labels:
{{ $app := include "elasticsearch.fullname" . -}}
{{ include "metadata.calculateLabels" (list . $app "pki-init" "init") | indent 4 }}
    name: ibm-elastic-stack-operator
    app.kubernetes.io/instance: elk-logging #may be something else
    app.kubernetes.io/managed-by: elasticstacks.elasticstack.ibm.com
    app.kubernetes.io/name: elasticstacks.elasticstack.ibm.com
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  template:
    metadata:
      labels:
{{ include "metadata.calculateLabels" (list . $app "secret-init" "init") | indent 8 }}
      annotations:
{{ include "metadata.calculateAnnotations" (list . ) | indent 8 }}
    spec:
{{ include "image.pullSecret" . | indent 6 }}
{{- if .Values.elasticsearch.client.tolerations }}
      tolerations:
{{ toYaml .Values.elasticsearch.client.tolerations | indent 6 }}
{{- end }}
{{- if .Values.elasticsearch.client.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.elasticsearch.client.nodeSelector | indent 8 }}
{{- end }}
      serviceAccountName: "{{ template "job.fullname" . }}"
      containers:
      - name: kubectl
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        image: {{ include "image.calculateImage" (list .Values.elasticsearch.pkiInitImage.repository .Values.elasticsearch.pkiInitImage.tag .Values.elasticsearch.pkiInitImage.digest) }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.elasticsearch.pkiInitImage.resources | indent 12 }}
        volumeMounts:
  {{- if eq .Values.security.ca.origin "external" }}
        - name: ca
          mountPath: /etc/icp-ca/chain-ca.pem
          subPath: chain-ca.pem
        - name: ca
          mountPath: /etc/icp-ca/signing-ca.pem
          subPath: signing-ca.pem
        - name: ca
          mountPath: /etc/icp-ca/signing-ca.key
          subPath: signing-ca.key
  {{- end }}
        env:
        - name: APP_NAME
          value: "{{ template "elasticsearch.fullname" . }}"
        - name: CHART_NAME_VERSION
          value: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        - name: COMPONENT_NAME
          value: "secret-init"
        - name: HERITAGE
          value: "{{ .Release.Service }}"
        - name: ROLE_NAME
          value: "initialization"
        - name: RELEASE_NAME_LABEL
          value: "{{ .Release.Name }}"
        - name: RELEASE_NAME
          value: "{{ template "fullname" . }}"
  {{- if eq .Values.security.ca.origin "external" }}
        - name: CA_LOCATION
          value: "/etc/icp-ca"
  {{- end }}
        - name: REQUIRED_CERT_ENTRY_COUNT
          value: "21"
        - name: CA_KEYSTORE_PASSWORD
          value: "{{ .Values.security.ca.keystore.password | b64enc }}"
        - name: CA_TRUSTSTORE_PASSWORD
          value: "{{ .Values.security.ca.truststore.password | b64enc }}"
        - name: APP_KEYSTORE_PASSWORD
          value: "{{ .Values.security.app.keystore.password | b64enc }}"
        - name: CERT1_NAME
          value: 'sgadmin'
        - name: CERT1_KEYSTORE
          value: 'jks'
        - name: CERT2_NAME
          value: 'kibana'
        - name: CERT2_KEYSTORE
          value: 'pem'
        - name: CERT2_SAN
          value: 'dns:kibana,dns:kibana.{{ .Release.Namespace }},dns:localhost,ip:127.0.0.1'
        - name: CERT2_KEY_FORMAT
          value: 'pkcs8'
        - name: CERT3_NAME
          value: 'logstash'
        - name: CERT3_KEYSTORE
          value: 'pem'
        - name: CERT3_SAN
          value: 'dns:logstash,dns:logstash.{{ .Release.Namespace }},dns:localhost,ip:127.0.0.1'  # filebeat need this to match the logstash service dns name
        - name: CERT3_KEY_FORMAT
          value: 'pkcs8'
        - name: CERT4_NAME
          value: 'logstash-monitoring'
        - name: CERT4_KEYSTORE
          value: 'jks'
        - name: CERT5_NAME
          value: 'logstash-elasticsearch'
        - name: CERT5_KEYSTORE
          value: 'jks'
        - name: CERT6_NAME
          value: 'filebeat'
        - name: CERT6_KEYSTORE
          value: 'pem'
        - name: CERT6_KEY_FORMAT
          value: 'pkcs1'
        - name: CERT7_NAME
          value: 'curator'
        - name: CERT7_KEYSTORE
          value: 'pem'
        - name: CERT7_SAN
          value: 'dns:localhost,ip:127.0.0.1'
        - name: CERT7_KEY_FORMAT
          value: 'pkcs1'
        - name: CERT7_KEY_ENCRYPTION
          value: 'false'
        - name: CERT8_NAME
          value: 'superuser'
        - name: CERT8_KEYSTORE
          value: 'pem'
        - name: CERT8_KEY_FORMAT
          value: 'pkcs1'
        - name: CERT9_NAME
          value: 'elasticsearch'
        - name: CERT9_KEYSTORE
          value: 'jks'
        - name: CERT9_SAN
          value: 'dns:elasticsearch,dns:elasticsearch.{{ .Release.Namespace }},dns:localhost,ip:127.0.0.1'
        - name: CERT10_NAME
          value: 'elasticsearch-transport'
        - name: CERT10_KEYSTORE
          value: 'jks'
        - name: CERT10_SAN
          value: 'dns:localhost,ip:127.0.0.1'
        - name: CERT11_NAME
          value: 'kibanarouter'
        - name: CERT11_KEYSTORE
          value: 'pem'
        - name: CERT11_KEY_FORMAT
          value: 'pkcs1'
        - name: CERT11_SAN
          value: 'dns:kibana,dns:kibana.{{ .Release.Namespace }}'
        - name: CERT12_NAME
          value: 'elasticsearch-router'
        - name: CERT12_SAN
          value: 'dns:elasticsearch,dns:elasticsearch.{{ .Release.Namespace }},dns:localhost,ip:127.0.0.1'
        - name: CERT12_DN
          value: 'CN=elasticsearch,OU=IBM Cloud Private'
        - name: CERT12_KEYSTORE
          value: 'pem'
        - name: CERT12_KEY_FORMAT
          value: 'pkcs1'
        - name: CERT12_KEY_ENCRYPTION
          value: 'false'
      restartPolicy: Never
      volumes:
  {{- if eq .Values.security.ca.origin "external" }}
        - name: ca
          secret:
            secretName: {{ .Values.security.ca.external.secretName }}
            items:
              - key: {{ .Values.security.ca.external.certFieldName }}
                path: chain-ca.pem
              - key: {{ .Values.security.ca.external.certFieldName }}
                path: signing-ca.pem
              - key: {{ .Values.security.ca.external.keyFieldName }}
                path: signing-ca.key
  {{- end }}
{{- end }}
