{{ template "cp-console.url.set" . -}}
apiVersion: v1
data:
  {{ if .Values.kibana.https }}
    dashboard-url: "https://{{ .Values.kibana.cp_console_host }}:{{ .Values.kibana.internal }}{{ .Values.kibana.ingress.path }}"
  {{ else }}
    dashboard-url: "http://{{ .Values.kibana.cp_console_host }}:{{ .Values.kibana.internal }}{{ .Values.kibana.ingress.path }}"
  {{ end }}
    logging-flavor: "common-services"
kind: ConfigMap
metadata:
  name: logging-access-config
  namespace: ibm-common-services
  labels:
{{ $app := include "elasticsearch.fullname" . -}}
{{ include "metadata.calculateLabels" (list . $app .Values.elasticsearch.data.name "proxy") | indent 4 }}
  selfLink: /api/v1/namespaces/ibm-common-services/configmaps/logging-access-config
