# {{ template "elk.settings.all.prepare" . -}}
# # 1. prepare kibana api url
# {{- if .Values.kibana.https }}
# protocol=https
# {{ else }}
# protocol=http
# {{- end }}

# endpoint={{ .Values.kibana.name }}
# port={{ .Values.kibana.internal }}
# path={{ .Values.kibana.ingress.path }}
# url="$protocol://$endpoint:$port$path"

# {{ template "kibana.settings.url.set" }}
apiVersion: v1
data:
  {{ if .Values.kibana.https }}
    dashboard-url: "https://{{ .Values.kibana.name }}:{{ .Values.kibana.internal }}{{ .Values.kibana.ingress.path }}"
  {{ else }}
    dashboard-url: "http://{{ .Values.kibana.name }}:{{ .Values.kibana.internal }}{{ .Values.kibana.ingress.path }}"
  {{ end }}
    logging-flavor: "common-services"
kind: ConfigMap
metadata:
  name: logging-flavor
  namespace: ibm-common-services
  labels:
{{ $app := include "elasticsearch.fullname" . -}}
{{ include "metadata.calculateLabels" (list . $app .Values.elasticsearch.data.name "proxy") | indent 4 }}
  selfLink: /api/v1/namespaces/ibm-common-services/configmaps/logging-flavor
